name: Ansible CI/CD with Docker

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  SSH_USER: ${{ vars.SSH_USER }}
  TARGET_HOST: ${{ vars.TARGET_HOST }}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}
  DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub with token
        run: |
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
